'use strict';
const AUTH_URL='https://pjkvfcvqibwcxordyxfv.supabase.co';
const AUTH_PUBLIC_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqa3ZmY3ZxaWJ3Y3hvcmR5eGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAxNDY1MDAsImV4cCI6MjEwNTcyMjUwMH0.xfcgnh7feO6_yFhiwcRP67kz_bh8H17pgzFNHxouNzU';
let authMode='signin',supabaseClient=null,currentUser=null,activeUserId=null;
function authErrorText(error){const message=String(error?.message||error||'').trim();if(/invalid login credentials/i.test(message))return 'כתובת המייל או הסיסמה אינם נכונים.';if(/email not confirmed/i.test(message))return 'צריך לאשר את כתובת המייל דרך ההודעה שנשלחה אליך.';if(/user already registered/i.test(message))return 'כתובת המייל כבר רשומה. נסה להתחבר.';if(/provider is not enabled|unsupported provider/i.test(message))return 'התחברות Google עדיין לא הופעלה ב‑Supabase. אפשר בינתיים להתחבר עם מייל.';if(/password should be at least/i.test(message))return 'הסיסמה צריכה להכיל לפחות 8 תווים.';return message||'הפעולה לא הצליחה. נסה שוב בעוד רגע.';}
function displayAuthError(message,isError=true){const status=$('#authStatus');status.textContent=message||'';status.classList.toggle('auth-error',Boolean(message)&&isError);}
function setAuthMode(mode){authMode=mode;const signup=mode==='signup';$('#authTitle').textContent=signup?'פתיחת חשבון':'התחברות';$('#authSubmit').textContent=signup?'יצירת חשבון':'התחברות';$('#authPasswordConfirmField').hidden=!signup;$('#authPassword').autocomplete=signup?'new-password':'current-password';displayAuthError('');}
async function activateSession(session){const user=session?.user;if(!session?.access_token||!user?.id)return;currentUser=user;if(activeUserId!==user.id){activeUserId=user.id;loadTripsForUser(user.id);loadProfileForUser(user.id);}$('#authGate').hidden=true;$('.app-shell').hidden=false;$('#storageStatus').textContent='שמירה במכשיר זה';$('#profileBtn').textContent=(user.email||'אני').slice(0,1).toLocaleUpperCase('he');$('#profileBtn').setAttribute('aria-label','החשבון של '+(user.email||''));}
async function showSignedOut(message=''){currentUser=null;activeUserId=null;$('#authGate').hidden=false;$('.app-shell').hidden=true;$('#authEmail').value='';$('#authPassword').value='';setAuthMode('signin');displayAuthError(message);}
async function submitAuth(event){event.preventDefault();const button=$('#authSubmit'),email=$('#authEmail').value.trim(),password=$('#authPassword').value;displayAuthError('');if(!supabaseClient){displayAuthError('שירות ההתחברות עדיין נטען. רענן את הדף ונסה שוב.');return;}if(!email||!password)return;if(authMode==='signup'&&password!==$('#authPasswordConfirm').value){displayAuthError('הסיסמאות אינן זהות.');return;}button.disabled=true;button.textContent=authMode==='signup'?'יוצר חשבון…':'מתחבר…';try{if(authMode==='signup'){const {data,error}=await supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;if(data.session)await activateSession(data.session);else{setAuthMode('signin');displayAuthError('שלחנו הודעת אישור לכתובת המייל שלך. אשר אותה ואז התחבר כאן.',false);}}else{const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error;await activateSession(data.session);}}catch(error){displayAuthError(authErrorText(error));}finally{button.disabled=false;button.textContent=authMode==='signup'?'יצירת חשבון':'התחברות';}}
async function googleSignIn(){const button=$('#googleSignIn');if(!supabaseClient){displayAuthError('שירות ההתחברות עדיין נטען. רענן את הדף ונסה שוב.');return;}button.disabled=true;displayAuthError('מעביר אותך להתחברות של Google…',false);try{const {error}=await supabaseClient.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname,queryParams:{prompt:'select_account'}}});if(error)throw error;}catch(error){displayAuthError(authErrorText(error));button.disabled=false;}}
async function signOut(){closeModal();if(supabaseClient)await supabaseClient.auth.signOut({scope:'local'});await showSignedOut('התנתקת מהחשבון.');}
async function initializeTriplyAuth(){try{$('#authStatus').textContent='מתחבר לשירות החשבונות…';const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2.117.0');supabaseClient=createClient(AUTH_URL,AUTH_PUBLIC_KEY,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true,flowType:'pkce',storageKey:'triply:supabase-auth'}});window.triplyAuth={getSession:async()=>{if(!supabaseClient)return null;const {data,error}=await supabaseClient.auth.getSession();if(error)throw error;return data.session;},getUser:()=>currentUser,signOut};supabaseClient.auth.onAuthStateChange((event,session)=>{queueMicrotask(async()=>{if(session)await activateSession(session);else if(event==='SIGNED_OUT')await showSignedOut();});});const {data,error}=await supabaseClient.auth.getSession();if(error)throw error;if(data.session)await activateSession(data.session);else await showSignedOut();}catch(error){await showSignedOut(authErrorText(error)||'לא ניתן לטעון את שירות ההתחברות. בדוק את החיבור ונסה שוב.');if(/failed to fetch|import|module/i.test(String(error?.message||'')))displayAuthError('לא הצלחנו לטעון את שירות הכניסה. בדוק את החיבור לאינטרנט ורענן את הדף.');}}
$('#authModeToggle').onclick=()=>setAuthMode(authMode==='signup'?'signin':'signup');
$('#authForm').onsubmit=submitAuth;
$('#googleSignIn').onclick=googleSignIn;
window.triplyAuth=null;
sessionStorage.removeItem('triply:ai-session');
setAuthMode('signin');
initializeTriplyAuth();
