'use strict';
const capabilities={ai:true,auth:true,places:false,documents:true};
let preferences={pace:'balanced',interests:'',profileNotes:'',restaurants:false};
let savedPlaces=[];
let profileStorageId='legacy';
const profileStorageKey=name=>name==='preferences'?'triply:preferences:'+profileStorageId:'triply:saved:'+profileStorageId;
function loadProfileForUser(userId){try{const marker=localStorage.getItem('triply:legacy-profile-owner');for(const name of ['preferences','saved']){const target=profileStorageKeyFor(name,userId),legacy=name==='preferences'?'triply:preferences':'triply:saved';if(localStorage.getItem(target)===null&&marker===null&&localStorage.getItem(legacy)!==null)localStorage.setItem(target,localStorage.getItem(legacy));}if(marker===null)localStorage.setItem('triply:legacy-profile-owner',userId);profileStorageId=userId;preferences={pace:'balanced',interests:'',profileNotes:'',restaurants:false,...JSON.parse(localStorage.getItem(profileStorageKey('preferences'))||'{}')};savedPlaces=JSON.parse(localStorage.getItem(profileStorageKey('saved'))||'[]');if(!Array.isArray(savedPlaces))savedPlaces=[];preferencesSummary();}catch{toast('חלק מההעדפות לא ניתנות לקריאה');}}
function profileStorageKeyFor(name,userId){return name==='preferences'?'triply:preferences:'+userId:'triply:saved:'+userId;}
try{preferences={...preferences,...JSON.parse(localStorage.getItem('triply:preferences')||'{}')};savedPlaces=JSON.parse(localStorage.getItem('triply:saved')||'[]');if(!Array.isArray(savedPlaces))savedPlaces=[];}catch{toast('חלק מההעדפות לא ניתנות לקריאה');}
const AI_SUPABASE_URL='https://pjkvfcvqibwcxordyxfv.supabase.co',AI_PUBLIC_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqa3ZmY3ZxaWJ3Y3hvcmR5eGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAxNDY1MDAsImV4cCI6MjEwNTcyMjUwMH0.xfcgnh7feO6_yFhiwcRP67kz_bh8H17pgzFNHxouNzU';
async function aiSession(){const session=await window.triplyAuth?.getSession();if(!session?.access_token)throw Error('צריך להתחבר לחשבון כדי להשתמש בתכנון AI.');return session;}
async function aiCall(mode,payload){const session=await aiSession();const response=await fetch(AI_SUPABASE_URL+'/functions/v1/trip-planner',{method:'POST',headers:{'apikey':AI_PUBLIC_KEY,'Authorization':'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({mode,...payload}),signal:AbortSignal.timeout(60000)});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'שירות ה-AI אינו זמין כעת.');return data;}
function preferencesSummary(){$('#preferencesSummary').textContent=`קצב ${preferences.pace==='relaxed'?'נינוח':preferences.pace==='busy'?'מלא':'מאוזן'}${preferences.interests?' · '+preferences.interests:''} · ${preferences.restaurants?'אפשר להציע מסעדות':'מסעדות רק לפי בקשה'}`;}
function openPreferences(){openModal(`<h2>העדפות הטיול שלי</h2><form id="preferencesForm"><div class="field"><label for="pace">קצב הטיול</label><select id="pace"><option value="relaxed">נינוח</option><option value="balanced">מאוזן</option><option value="busy">מלא</option></select></div><div class="field"><label for="interests">מה מעניין אתכם?</label><textarea id="interests" maxlength="1000" placeholder="מוזיאונים, טבע, קניות…">${escapeHTML(preferences.interests)}</textarea></div><div class="field"><label for="profileNotes">מה עוד כדאי למתכנן לזכור?</label><textarea id="profileNotes" maxlength="1500" placeholder="למשל: מעדיפים הליכה קצרה, אוהבים אדריכלות, לא רוצים ימים עמוסים">${escapeHTML(preferences.profileNotes||'')}</textarea><small>הערות מהשיחה נשמרות במכשיר הזה. אפשר לערוך או למחוק אותן כאן.</small></div><label class="check-row"><input type="checkbox" id="restaurants" ${preferences.restaurants?'checked':''}> אפשר להציע מסעדות גם בלי שאבקש</label><p>ההעדפות נשמרות במכשיר ומשמשות לבקשות התכנון שלכם.</p><p id="preferencesError" role="alert"></p><button class="primary-btn">שמירת העדפות</button></form>`);$('#pace').value=preferences.pace;$('#preferencesForm').onsubmit=e=>{e.preventDefault();const next={pace:$('#pace').value,interests:$('#interests').value.trim(),profileNotes:$('#profileNotes').value.trim().slice(0,1500),restaurants:$('#restaurants').checked};try{localStorage.setItem(profileStorageKey('preferences'),JSON.stringify(next));preferences=next;preferencesSummary();closeModal();toast('ההעדפות נשמרו');}catch{$('#preferencesError').textContent='לא ניתן לשמור במכשיר';}};}
function downloadText(name,content,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function exportTrip(){const t=currentTrip();if(!t)return;const lines=[`הטיול: ${t.city}`,`${dateLabel(t.start)} – ${dateLabel(t.end)} · ${t.people} נוסעים`,`מלון / יציאה: ${t.hotel||'לא הוגדר'}`];for(const day of TripModel.dates(t.start,t.end)){lines.push('\n'+dateLabel(day));const schedule=t.dailySchedule?.find(item=>item.date===day);if(schedule){lines.push(`קימה ${schedule.wakeTime} · שינה ${schedule.sleepTime}`);for(const block of schedule.blocks)lines.push(`${block.startTime}–${block.endTime} · ${block.activity}${block.placeName?' · '+block.placeName:''}`);}else for(const s of t.stops.filter(s=>s.date===day).sort((a,b)=>a.time.localeCompare(b.time)))lines.push(`${s.time} · ${s.name} · ${s.duration} דקות${s.notes?' · '+s.notes:''}`);}lines.push('\nהוצאות ('+t.currency+')');for(const e of t.expenses)lines.push(`${e.name}: ${e.amount.toFixed(2)} · ${e.shared?'משותפת':'אישית'}`);downloadText('triply-itinerary.txt',lines.join('\n'),'text/plain;charset=utf-8');}
function openSettings(){openModal(`<h2>הגדרות ונתונים</h2><p>הטיולים נשמרים בחשבון שלך ומסונכרנים בין המכשירים. מסמכים מצורפים נשמרים רק בדפדפן הזה.</p><button class="secondary-btn" id="settingsPreferences">העדפות תכנון</button><button class="secondary-btn" id="backupData">הורדת גיבוי טיולים</button><p>גיבוי הטיולים כולל מסלולים והוצאות. מסמכים מצורפים יש להוריד בנפרד מתוך הטיול.</p><button class="secondary-btn" id="legacyData">הורדת הנתונים מהגרסה הקודמת</button><button class="secondary-btn" id="accountSettings">חשבון ושיתוף</button>`);$('#settingsPreferences').onclick=openPreferences;$('#backupData').onclick=()=>downloadText('triply-backup.json',JSON.stringify({version:2,trips:state.trips,preferences,savedPlaces},null,2));$('#legacyData').onclick=()=>{const old=localStorage.getItem('triplyTrips');if(!old){toast('לא נמצאו נתונים מהגרסה הקודמת');return;}downloadText('triply-legacy.json',old);};$('#accountSettings').onclick=openAccount;}
function openAccount(){const user=window.triplyAuth?.getUser(),email=user?.email||'חשבון מחובר';openModal(`<h2>החשבון שלך</h2><p>מחובר כ־${escapeHTML(email)}.</p><p>טיולים, העדפות והוצאות נשמרים במכשיר הזה. הכניסה לחשבון עדיין לא מסנכרנת אותם למכשירים אחרים או משתפת אותם עם חברים.</p><button class="secondary-btn" id="accountExport">הורדת גיבוי טיולים</button><button class="secondary-btn" id="accountSignOut">התנתקות</button><p id="accountStatus" role="status"></p>`);$('#accountExport').onclick=()=>downloadText('triply-backup.json',JSON.stringify({version:2,trips:state.trips,preferences,savedPlaces},null,2));$('#accountSignOut').onclick=async()=>{const button=$('#accountSignOut');button.disabled=true;$('#accountStatus').textContent='מתנתק…';await window.triplyAuth?.signOut();};}
function openSaved(){openModal(`<h2>מקומות שמורים</h2><form id="savePlaceForm"><div class="field"><label for="savedName">שם המקום והעיר</label><input id="savedName" required maxlength="200" placeholder="למשל: British Museum, London"></div><button class="primary-btn">שמירת מקום</button></form><div id="savedList"></div>`);const render=()=>{$('#savedList').innerHTML=savedPlaces.length?savedPlaces.map(p=>`<div class="member-row"><span>${escapeHTML(p.name)}</span><button class="small-btn" data-saved-map="${p.id}">מפה ↗</button><button class="small-btn" data-saved-delete="${p.id}" aria-label="מחיקת ${escapeHTML(p.name)}">הסרה</button></div>`).join(''):'<p>אין עדיין מקומות שמורים.</p>';$$('[data-saved-map]').forEach(b=>b.onclick=()=>window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(savedPlaces.find(p=>p.id===b.dataset.savedMap).name),'_blank','noopener'));$$('[data-saved-delete]').forEach(b=>b.onclick=()=>{const place=savedPlaces.find(p=>p.id===b.dataset.savedDelete);if(!place||!confirm(`להסיר את ${place.name} מהמקומות השמורים?`))return;const next=savedPlaces.filter(p=>p.id!==b.dataset.savedDelete);try{localStorage.setItem(profileStorageKey('saved'),JSON.stringify(next));savedPlaces=next;render();}catch{toast('לא ניתן לשמור');}});};$('#savePlaceForm').onsubmit=e=>{e.preventDefault();const name=$('#savedName').value.trim();if(!name)return;const next=[...savedPlaces,{id:crypto.randomUUID(),name}];try{localStorage.setItem(profileStorageKey('saved'),JSON.stringify(next));savedPlaces=next;$('#savedName').value='';render();}catch{toast('לא ניתן לשמור');}};render();}
function openExplore(){const t=currentTrip();openModal(`<h2>חיפוש לקראת הטיול</h2><form id="exploreForm"><div class="field"><label for="exploreCity">יעד</label><input id="exploreCity" required value="${escapeHTML(t?.city||'')}" placeholder="לאן נוסעים?"></div><div class="field-grid"><div class="field"><label for="exploreStart">יציאה</label><input id="exploreStart" type="date" required value="${t?.start||''}"></div><div class="field"><label for="exploreEnd">חזרה</label><input id="exploreEnd" type="date" required value="${t?.end||''}"></div></div><div class="field"><label for="exploreKind">מה לחפש?</label><select id="exploreKind"><option value="flights">טיסות</option><option value="hotels">לינה</option><option value="attractions">אטרקציות</option><option value="restaurants">מסעדות</option></select></div><p>תוצאות, מחירים וזמינות יופיעו אצל ספק החיפוש. לא מתבצע תשלום באפליקציה.</p><p id="exploreError" role="alert"></p><button class="primary-btn">פתיחת חיפוש ↗</button></form>`);$('#exploreForm').onsubmit=e=>{e.preventDefault();try{TripModel.dates($('#exploreStart').value,$('#exploreEnd').value);const city=$('#exploreCity').value.trim(),kind=$('#exploreKind').value;let url;if(kind==='attractions'||kind==='restaurants')url='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(city+' '+(kind==='attractions'?'tourist attractions':'restaurants'));else url='https://www.google.com/search?q='+encodeURIComponent((kind==='flights'?'flights to ':'hotels in ')+city+' '+$('#exploreStart').value+' '+$('#exploreEnd').value);window.open(url,'_blank','noopener');}catch(err){$('#exploreError').textContent=err.message;}};}
function localDayIndex(value){const names={ראשון:1,ראשונה:1,שני:2,שנייה:2,שלישי:3,שלישית:3,רביעי:4,רביעית:4,חמישי:5,חמישית:5,שישי:6,שישית:6,שביעי:7,שביעית:7,שמיני:8,שמינית:8};const word=value.replace(/^ה/,'');return /^\d+$/.test(word)?Number(word):names[word];}
function findStop(trip,name){const query=name.trim().toLocaleLowerCase('he');return trip.stops.find(stop=>stop.name.toLocaleLowerCase('he')===query)||trip.stops.find(stop=>stop.name.toLocaleLowerCase('he').includes(query));}
function localPlan(trip,text){const clean=text.trim().replace(/\s+/g,' '),days=TripModel.dates(trip.start,trip.end);let m=clean.match(/^הוסף(?:\s+את)?\s+(.+?)\s+ביום\s+(ה?[\dא-ת]+)\s+בשעה\s+(\d{1,2}:\d{2})(?:\s+למשך\s+(\d+)\s*(?:דקות?|דק׳?))?$/);if(m){const day=localDayIndex(m[2]);if(!day||!days[day-1])throw Error('היום שביקשתם אינו נמצא בטווח הטיול');return {message:'זיהיתי הוספה למסלול בעיבוד מקומי. בדקו ואשרו את השינוי.',operations:[{type:'add',name:m[1].trim(),date:days[day-1],time:m[3].padStart(5,'0'),duration:Number(m[4]||60),notes:''}]};}m=clean.match(/^העבר(?:\s+את)?\s+(.+?)\s+ליום\s+(ה?[\dא-ת]+)\s+בשעה\s+(\d{1,2}:\d{2})$/);if(m){const stop=findStop(trip,m[1]),day=localDayIndex(m[2]);if(!stop)throw Error('לא מצאתי תחנה בשם הזה במסלול');if(!day||!days[day-1])throw Error('היום שביקשתם אינו נמצא בטווח הטיול');return {message:'זיהיתי העברה של תחנה בעיבוד מקומי. בדקו ואשרו את השינוי.',operations:[{type:'update',id:stop.id,date:days[day-1],time:m[3].padStart(5,'0')}]};}m=clean.match(/^(?:מחק|הסר)(?:\s+את)?\s+(.+?)\s*(?:מהמסלול)?$/);if(m){const stop=findStop(trip,m[1]);if(!stop)throw Error('לא מצאתי תחנה בשם הזה במסלול');return {message:'זיהיתי הסרה של תחנה בעיבוד מקומי. בדקו ואשרו את השינוי.',operations:[{type:'remove',id:stop.id}]};}return null;}
function openChat(){const t=currentTrip();if(!t){toast('בחרו טיול כדי להתחיל לתכנן');return;}let sending=false;openModal(`<div class="chat-heading"><h2>מתכננים את ${escapeHTML(t.city)}</h2><p>אפשר לבקש שינוי יום, שעה, הוספה או הסרה. כל שינוי יוצג לאישור.</p></div><div id="chatHistory" class="chat-history" role="log" aria-live="polite" aria-label="התכתבות עם מתכנן הטיול"></div><div id="proposalPanel"></div><form id="chatForm" class="chat-composer"><label for="chatMessage">מה תרצו לשנות או לתכנן?</label><textarea id="chatMessage" rows="3" maxlength="3000" required placeholder="למשל: העבר את הביקור במוזיאון ליום השני בשעה 10:00"></textarea><div class="chat-send-row"><p id="chatStatus" role="status"></p><button id="chatSend" class="primary-btn" type="submit">שליחה</button></div></form>`);$('#modalContent').classList.add('chat-dialog');const originalClose=closeModal;$('.modal-close').onclick=()=>{originalClose();$('#modalContent').classList.remove('chat-dialog');};
const draw=()=>{$('#chatHistory').innerHTML=t.chat.length?t.chat.map(m=>`<div class="message ${m.role==='user'?'from-user':'from-assistant'}"><b>${m.role==='user'?'אתם':'מתכנן הטיול'}</b><p>${escapeHTML(m.text)}</p></div>`).join(''):'<div class="message from-assistant"><p>במה אפשר לעזור בתכנון? הודעה תישלח לשירות התכנון רק לאחר לחיצה על שליחה.</p></div>';$('#chatHistory').scrollTop=$('#chatHistory').scrollHeight;};draw();
$('#chatMessage').onkeydown=e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();$('#chatForm').requestSubmit();}};
$('#chatForm').onsubmit=async e=>{
  e.preventDefault();if(sending)return;
  const text=$('#chatMessage').value.trim();if(!text)return;
  sending=true;
  const submit=$('#chatSend'),status=$('#chatStatus'),history=$('#chatHistory'),proposalPanel=$('#proposalPanel');
  submit.disabled=true;status.textContent='בודק את המסלול…';proposalPanel.replaceChildren();
  const snapshot=JSON.stringify(t.stops);
  t.chat.push({role:'user',text});
  try{
    save();draw();$('#chatMessage').value='';
    const data=await aiCall('plan',{message:text,trip:{id:t.id,city:t.city,start:t.start,end:t.end,people:t.people,hotel:t.hotel,stops:t.stops,travelDetails:t.travelDetails},preferences,history:t.chat.slice(-12)});
    if(typeof data.message!=='string')throw Error('שירות התכנון החזיר תשובה לא תקינה');
    t.chat.push({role:'assistant',text:data.message});save();
    if(!history.isConnected)return;
    draw();status.textContent='';
    const hasOperations=Array.isArray(data.operations)&&data.operations.length>0;
    const hasSchedule=Array.isArray(data.dailySchedule)&&data.dailySchedule.length>0;
    if(hasOperations||hasSchedule){
      const preview=TripPlanning.apply(t,data.operations||[]);
      const schedule=hasSchedule?TripPlanning.validateSchedule(t,data.dailySchedule):null;
      proposalPanel.innerHTML=`<h3>ההצעה למסלול</h3><ul>${preview.changes.map(x=>'<li>'+escapeHTML(x)+'</li>').join('')}${schedule?'<li>לוח זמנים מלא ל־'+schedule.length+' ימים, מהקימה ועד השינה</li>':''}</ul><p>ההצעה עדיין לא נשמרה. זמני מעבר ופתיחה הם הערכות, אלא אם צוין במפורש שאומתו.</p><div class="modal-actions"><button id="rejectProposal" class="secondary-btn">ביטול ההצעה</button><button id="acceptProposal" class="primary-btn">אישור ועדכון המסלול</button></div>`;
      $('#rejectProposal').onclick=()=>{proposalPanel.replaceChildren();status.textContent='ההצעה בוטלה. המסלול לא השתנה.';};
      $('#acceptProposal').onclick=()=>{
        if(JSON.stringify(t.stops)!==snapshot){status.textContent='המסלול השתנה מאז ההצעה. שלח בקשה חדשה כדי למנוע דריסה.';proposalPanel.replaceChildren();return;}
        const oldStops=t.stops,oldSchedule=t.dailySchedule,oldSnapshot=t.scheduleStopSnapshot;
        t.stops=preview.stops;
        if(schedule){t.dailySchedule=schedule;t.scheduleStopSnapshot=JSON.stringify(preview.stops);}
        else if(t.dailySchedule)t.scheduleStopSnapshot='';
        try{save();proposalPanel.replaceChildren();status.textContent='המסלול נשמר. אפשר לראות את לוח היום המלא בלשונית מסלול.';if(currentTrip()?.id===t.id)renderStops();}
        catch{t.stops=oldStops;t.dailySchedule=oldSchedule;t.scheduleStopSnapshot=oldSnapshot;status.textContent='לא ניתן לשמור את השינוי';}
      };
    }
  }catch(err){if(status.isConnected){status.textContent=err.message||'הבקשה נכשלה. אפשר לנסות שוב.';$('#chatMessage').value=text;}}
  finally{sending=false;if(submit.isConnected)submit.disabled=false;}
};
}
$('#profileBtn').onclick=openAccount;$('#inviteBtn').onclick=openAccount;$('#settingsBtn').onclick=openSettings;$('#preferencesBtn').onclick=openPreferences;$('#savedBtn').onclick=openSaved;$('#exploreBtn').onclick=openExplore;$('#aiPlanBtn').onclick=openChat;$('#exportTripBtn').onclick=exportTrip;
$('#archiveTripBtn').onclick=()=>{const t=currentTrip(),old=t.archived;t.archived=!old;try{save();renderTrips();showView('homeView');toast(t.archived?'הטיול הועבר לארכיון':'הטיול שוחזר');}catch{t.archived=old;toast('לא ניתן לשמור');}};
$('#allTripsBtn').onclick=()=>{showArchived=!showArchived;$('#allTripsBtn').textContent=showArchived?'הסתרת ארכיון':'כולל ארכיון';renderTrips();};
preferencesSummary();
